[workspace]
members = ["tested-trait", "tested-trait-macros"]
resolver = "2"

[workspace.package]
edition = "2021"
authors = ["Max Heller <max.a.heller@gmail.com>"]
categories = ["development-tools", "rust-patterns"]
repository = "https://github.com/max-heller/tested-trait"
